### ISSUE TITLE
技术咨询，实时拉流直播时声音出不来

### ISSUE THREAD

**Issue by jermyLin** [ZLMediaKit/ZLMRTCClient.js#10]
推流时，音频已经带上，但是，直播的时候，没有声音出来，录制下来的mp4是有声音的，目前看是rtmp那边不支持当前声音的编码，想问下如何配置音频的编码格式，或者有没有音频这块相关的api，在vlc上看的编码格式是: A52 Audio (aka AC3)(a52b)，如何转成AAC格式编码

**Comment by xiongguangjie** [comment]
这个需要转码，或者你使用wasm技术开发播放器，这个是rtc播放器，是不支持这个音频编码的
