### ISSUE TITLE
chrome内核77播放不了，报错

### ISSUE THREAD

**Issue by liuyiling0221** [ZLMediaKit/ZLMRTCClient.js#3]
出错代码 https://github.com/ZLMediaKit/ZLMRTCClient.js/blob/29fbe27c81086706b5d66438c430a8287287fcd5/src/endpoint/endpoint.js#L98
报错内容 [RTCPusherPlayer] DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to set remote audio description streams.

**Comment by xia-chu** [comment]
这个问题可能无法处理   不知道answer sdp哪里让chrome 不兼容了，而且chrome77太老了，建议用户升级下啊

**Comment by LemonTao76** [comment]
像我们这种要求40版本chrome的是不是可以放弃了？

**Comment by xia-chu** [comment]
> 像我们这种要求40版本chrome的是不是可以放弃了？

如果你不会调试修改zlm，建议放弃

**Comment by xia-chu** [comment]
兼容性问题 不要全指望项目作者，毕竟是开源的，自己要学会用和改。
这些兼容性问题，我去哪里给你找老版本的浏览器安装包啊

**Comment by xxxxxxbin6** [comment]
@xiongguangjie  大佬,我现在在谷歌40版本开发,拉取webrtc流的API已降到能适配40版本的浏览器,但是在播放流的时候,video标签是黑屏现象,src是以blob开头的url,你知道为啥吗?

**Comment by xxxxxxbin6** [comment]
@liuyiling0221 
![image](https://user-images.githubusercontent.com/60058377/156328403-abd80c57-fed1-4572-8873-2612dadbdfab.png)

**Comment by xia-chu** [comment]
这个issue合并到 https://github.com/ZLMediaKit/ZLMediaKit/issues/1359 讨论吧，先关闭。那个issue更详实点
