### ISSUE TITLE
window firefox版本89  93 都播放不了

### ISSUE THREAD

**Issue by ZLJ599** [ZLMediaKit/ZLMRTCClient.js#4]
![261643353820_ pic](https://user-images.githubusercontent.com/9264066/151503930-d55dc411-d74b-4dea-b7c0-fb25d231294d.jpg)
![251643353820_ pic](https://user-images.githubusercontent.com/9264066/151503945-f6eb5c8c-00b6-49c2-93ec-a725e9fec3b4.jpg)
![241643353819_ pic 2](https://user-images.githubusercontent.com/9264066/151503958-29718518-6468-42af-a914-700d2790f20a.jpg)

只提示URI有问题。  在另一台ubuntu的firefox 可以正常播放。

**Comment by xia-chu** [comment]
我没这个测试环境 Firefox可有错误输出？
