### ISSUE TITLE
icecandidate是如何获取和发送到远端的？

### ISSUE THREAD

**Issue by N-E-K-O** [ZLMediaKit/ZLMRTCClient.js#6]
您好，想请教下 , 我在 ZLMRTCClient.js 中 endpoint.js 里并没有发现有关 icecandidate 获取和发送的相关逻辑。和自己学习了解到的webrtc 创建通道的流程不太一致。所以想问下这部分可能不添加吗？还是在别的地方有处理？

**Comment by xia-chu** [comment]
> 下 , 我在 ZLMRTCClient.js 中 endpoint.js 里并没有发现有关 icecandidate 获取和发送的相关逻辑。和自己学习了解到的webrtc 创建通道的流程不太一致。所以想问下这部分可能不添加吗？还是在别的地方有处理？

因为zlm是sfu的webrtc模式 所以它不需要客户端提供icecandidate 自然不需要ZLMRTCClient.js 收集icecandidate

**Comment by xia-chu** [comment]
> > 下 , 我在 ZLMRTCClient.js 中 endpoint.js 里并没有发现有关 icecandidate 获取和发送的相关逻辑。和自己学习了解到的webrtc 创建通道的流程不太一致。所以想问下这部分可能不添加吗？还是在别的地方有处理？
> 
> 因为zlm是sfu的webrtc模式 所以它不需要客户端提供icecandidate 自然不需要ZLMRTCClient.js 收集icecandidate

**Comment by N-E-K-O** [comment]
> > 下 , 我在 ZLMRTCClient.js 中 endpoint.js 里并没有发现有关 icecandidate 获取和发送的相关逻辑。和自己学习了解到的webrtc 创建通道的流程不太一致。所以想问下这部分可能不添加吗？还是在别的地方有处理？
> 
> 因为zlm是sfu的webrtc模式 所以它不需要客户端提供icecandidate 自然不需要ZLMRTCClient.js 收集icecandidate

了解了。感谢~
