### ISSUE TITLE
Jetson nano FireFox cannot play

### ISSUE THREAD

**Issue by vtn98** [ZLMediaKit/ZLMRTCClient.js#7]
Hi @xia-chu,
I couldn't play webrtc on Firefox (version: 112.0.1), I received an error:
offer answer 交换失败 "Assertion failed: (have_active_media, 必须确保最少有一个活跃的track), function checkValid, file /ZLMediaKit/webrtc/Sdp.cpp, line 1336."
Could you help me to solve this error, please?
Thank you.

**Comment by xia-chu** [comment]
Is your video H265 codec?

**Comment by vtn98** [comment]
No, it's H264 codec

**Comment by xia-chu** [comment]
Please upload your zlmediakit's log.

**Comment by vtn98** [comment]
# request:
POST /index/api/webrtc?app=proxy&type=play&stream=test
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate
Accept-Language : en-US,en;q=0.5
Connection : keep-alive
Content-Length : 1925
Content-Type : text/plain;charset=utf-8
Host : 192.168.2.22:5000
Origin : http://192.168.2.22:1234
Referer : http://192.168.2.22:1234/
User-Agent : Mozilla/5.0 (X11; Ubuntu; Linux aarch64; rv:109.0) Gecko/20100101 Firefox/112.0
# content:
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 8140169401645887068 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 D5:FC:ED:16:A2:39:A5:D8:3C:72:D5:FE:F2:64:E4:E3:CB:08:D0:23:39:15:A1:BF:7E:F0:2F:8E:77:52:99:25
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:124 apt=120
a=fmtp:121 max-fs=12288;max-fr=60
a=fmtp:125 apt=121
a=ice-pwd:6b4d4883f110eddbe9996c7a1297f785
a=ice-ufrag:bfcd9631
a=mid:0
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=setup:actpass
a=ssrc:3590031864 cname:{1deb58e2-c1f2-44f5-bdfb-bb80b7976db6}
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:6b4d4883f110eddbe9996c7a1297f785
a=ice-ufrag:bfcd9631
a=mid:1
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=setup:actpass
a=ssrc:4185803384 cname:{1deb58e2-c1f2-44f5-bdfb-bb80b7976db6}

# response:
{
        "code" : -400,
        "msg" : "Assertion failed: (have_active_media, \u5fc5\u987b\u786e\u4fdd\u6700\u5c11\u6709\u4e00\u4e2a\u6d3b\u8dc3\u7684track), function checkValid, file /home/ubuntu/mediaprocess/ZLMediaKit/webrtc/Sdp.cpp, line 1336."
}


2023-04-20 13:46:45.059 I [MediaServer] [2313-event poller 5] WebRtcTransport.cpp:417 ~WebRtcTransportImp | zlm_1926

**Comment by xia-chu** [comment]
You firefox's offer sdp do not support H264.

**Comment by code-qizi** [comment]
请问解决了吗，我这边火狐也播放不了

**Comment by xia-chu** [comment]
> 请问解决了吗，我这边火狐也播放不了

先确认下视频是什么格式 现在还不支持264的老浏览器很少了

**Comment by code-qizi** [comment]
> > 求解决了吗，我这篇文章火狐也播放不了
> 
> 先确认下视频是什么格式现在不太支持264的老浏览器了

视频格式是h264的，在360，Edge...,上都可以正常播放

**Comment by code-qizi** [comment]
> > > 求解决了吗，我这篇文章潍坊也播放不了
> > 
> > 
> > 先确认下视频是什么格式现在不太支持264的老浏览器了
> 
> 视频格式是h264的，在360，Edge...，上都可以正常播放

有可能是https的原因，我在本地测试是正常的

**Comment by xia-chu** [comment]
能正常播放就ok了 不支持264的浏览器 也没办法 流是264的
