### ISSUE TITLE
Get the transmission rate of the video

### ISSUE THREAD

**Issue by Agility6** [ZLMediaKit/ZLMRTCClient.js#8]
hello, Is there a way to monitor the real-time transmission rate of live video?

**Comment by xia-chu** [comment]
Now zlmediakit support whip/whep, you can also use other client.

**Comment by xiongguangjie** [comment]
you can custom  develop the player reference https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats
